schema_version: 20180708
name: quotation
version: 0.0.2
runtime: java
build_image: fnproject/fn-java-fdk-build:jdk11-1.0.85
run_image: fnproject/fn-java-fdk:jre11-1.0.85
cmd: org.paumard.oc2018.quotation.Quotation::quote
triggers:
- name: quotation
  type: http
  source: /quotation
