schema_version: 20180708
name: destinationrecommandation
version: 0.0.1
runtime: java
build_image: fnproject/fn-java-fdk-build:jdk9-1.0.75
run_image: fnproject/fn-java-fdk:jdk9-1.0.75
cmd: org.paumard.oc2018.destination.Recommandation::recommand
format: http-stream
triggers:
- name: destinationRecommandation
  type: http
  source: /destinationRecommandation
