schema_version: 20180708
name: weatherforecast
version: 0.0.3
runtime: java
build_image: fnproject/fn-java-fdk-build:jdk9-1.0.75
run_image: fnproject/fn-java-fdk:jdk9-1.0.75
cmd: org.paumard.oc2018.weather.WeatherForecast::forecast
format: http-stream
triggers:
- name: weatherforecast
  type: http
  source: /weatherforecast
