schema_version: 20180708
name: rec
version: 0.0.6
runtime: java
build_image: fnproject/fn-java-fdk-build:jdk11-1.0.85
run_image: fnproject/fn-java-fdk:jre11-1.0.85
cmd: org.paumard.oc2018.travel.Recommendation::get
triggers:
- name: agency
  type: http
  source: /agency
